export default interface BattleRoyalStats {
    data: {
        account: {
            id: string;
            name: string;
        }
        battlePass: {
            level: number;
            progress: number;
        }
        image: string;
        stats: {
            all:{
                overall: {
                    score: number;
                    scorePerMin: number;
                    scorePerMatch: number;
                    wins: number;
                    top3: number;
                    top4: number;
                    top5: number;
                    top6: number;
                    top10: number;
                    top12: number;
                    top25: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                solo: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch:any;
                    wins: number;
                    top10: number;
                    top25: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: number;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                duo: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top5: number;
                    top12: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: number;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                trio: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top3: number;
                    top6: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                squad: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top3: number;
                    top6: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd:any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date
                }
                ltm: {
                    score: number;
                    scorePerMin: number
                    scorePerMatch: number;
                    wins: number;
                    kills: number;
                    killsPerMIn: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
            }
            keyboardMouse: {
                overall: {
                    score: number;
                    scorePerMin: number;
                    scorePerMatch: number;
                    wins: number;
                    top3: number;
                    top4: number;
                    top5: number;
                    top6: number;
                    top10: number;
                    top12: number;
                    top25: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                solo: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch:any;
                    wins: number;
                    top10: number;
                    top25: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: number;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                duo: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top5: number;
                    top12: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: number;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                trio: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top3: number;
                    top6: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                squad: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top3: number;
                    top6: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd:any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date
                }
                ltm: {
                    score: number;
                    scorePerMin: number
                    scorePerMatch: number;
                    wins: number;
                    kills: number;
                    killsPerMIn: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
            }
            gamepad: {
                overall: {
                    score: number;
                    scorePerMin: number;
                    scorePerMatch: number;
                    wins: number;
                    top3: number;
                    top4: number;
                    top5: number;
                    top6: number;
                    top10: number;
                    top12: number;
                    top25: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                solo: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch:any;
                    wins: number;
                    top10: number;
                    top25: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: number;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                duo: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top5: number;
                    top12: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: number;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                trio: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top3: number;
                    top6: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                squad: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top3: number;
                    top6: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd:any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date
                }
                ltm: {
                    score: number;
                    scorePerMin: number
                    scorePerMatch: number;
                    wins: number;
                    kills: number;
                    killsPerMIn: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
            }
            touch: {
                overall: {
                    score: number;
                    scorePerMin: number;
                    scorePerMatch: number;
                    wins: number;
                    top3: number;
                    top4: number;
                    top5: number;
                    top6: number;
                    top10: number;
                    top12: number;
                    top25: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                solo: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch:any;
                    wins: number;
                    top10: number;
                    top25: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: number;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                duo: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top5: number;
                    top12: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: number;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                trio: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top3: number;
                    top6: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
                squad: {
                    score: number;
                    scorePerMin: any;
                    scorePerMatch: any;
                    wins: number;
                    top3: number;
                    top6: number;
                    kills: number;
                    killsPerMin: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd:any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date
                }
                ltm: {
                    score: number;
                    scorePerMin: number
                    scorePerMatch: number;
                    wins: number;
                    kills: number;
                    killsPerMIn: any;
                    killsPerMatch: any;
                    deaths: number;
                    kd: any;
                    matches: number;
                    winRate: any;
                    minutesPlayed: number;
                    playersOutlived: number;
                    lastModified: Date;
                }
            }
        }
    }
}